[project]
name = "patchtst"
version = "0.1.0"
description = "PatchTST forecasting experiments"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "tsai",
    "fastai",
    "numpy",
    "pandas",
    "scipy",
    "scikit-learn",
    "torch[device-gfx1102]",
    "torchvision[device-gfx1102]",
    "torchaudio",
    "rocm[libraries,device-gfx1102]",
    "fastcore",
    "ipykernel",
    "jupyter-core",
]

[tool.uv]
index-strategy = "unsafe-first-match"
preview-features = ["centralized-project-envs"]
environments = [
    "sys_platform == 'win32'",
    "sys_platform == 'linux'",
]

override-dependencies = [
    "triton; sys_platform == 'linux'",
]

[tool.uv.sources]
torch = { index = "amd-rocm" }
torchvision = { index = "amd-rocm" }
torchaudio = { index = "amd-rocm" }
rocm = { index = "amd-rocm" }
triton = { index = "amd-rocm" }

[[tool.uv.index]]
name = "amd-rocm"
url = "https://repo.amd.com/rocm/whl-multi-arch/"

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
