[project]
name = "patchtst"
version = "0.1.0"
description = "PatchTST forecasting experiments"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    # "tsai==0.4.1 ; sys_platform == 'win32'",
    "tsai==1.0.1",
    "fastai>=2.8.7",
    "numpy>=1.26",
    "pandas>=2.2",
    "scipy>=1.17",
    "scikit-learn",
    "torch[device-gfx1102]==2.12.0+rocm7.14.0",
    "torchvision[device-gfx1102]==0.27.0+rocm7.14.0",
    "torchaudio==2.11.0+rocm7.14.0",
    "rocm[libraries,device-gfx1102]==7.14.0",
    "fastcore>=1.13.2,<2",
    "ipykernel",
    "jupyter-core>=5.9.1",
]

[tool.uv]
index-strategy = "unsafe-first-match"
preview-features = ["centralized-project-envs"]
environments = [
    "sys_platform == 'win32'",
    "sys_platform == 'linux'",
]
override-dependencies = [
    "torch[device-gfx1102]==2.12.0+rocm7.14.0",
    "triton==3.7.1+git0263a6a6.rocm7.14.0 ; sys_platform == 'linux'",
]

[tool.uv.sources]
torch = { index = "amd-rocm" }
torchvision = { index = "amd-rocm" }
torchaudio = { index = "amd-rocm" }
rocm = { index = "amd-rocm" }

[[tool.uv.index]]
name = "amd-rocm"
url = "https://repo.amd.com/rocm/whl-multi-arch/"

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"

